version: '3.7'

services:
  flutter:
    container_name: flutter
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    volumes:
      - type: bind
        source: ./app/hello_world
        target: /application
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - type: bind
        source: /dev/kvm
        target: /dev/kvm
    entrypoint: flutter
