version: '3.7'

services:
  flutter:
    container_name: flutter
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/hello_world:/application
    entrypoint: flutter

volumes:
  usb:
