version: '3.7'

services:
  flutter:
    container_name: flutter
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - type: bind
        source: /dev/bus
        target: /dev/bus
      - ./app/hello_world:/application
    entrypoint: flutter

