version: '3.7'

services:
  app_flutter:
    container_name: app_flutter
    image: app_flutter
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    ports:
      - 42087:42087
    volumes:
      - type: bind
        source: ./app/hello_world
        target: /application
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - type: bind
        source: /dev/kvm
        target: /dev/kvm
    command: bash -c "flutter run"
