version: '3.7'

services:
  flutter:
    container_name: flutter
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: flutter
