version: '3.7'

services:
  flutter:
    container_name: flutter
    build:
      network: host
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/kvm:/dev/kvm
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/hello_world:/application
    entrypoint: flutter

